#release configuration
#Wed Apr 15 09:28:56 CEST 2026
completedPhase=generate-release-poms
exec.additionalArguments=-P jahia-academy
exec.snapshotReleasePluginAllowed=false
preparationGoals=clean install
project.dev.org.jahia.modules\:addstuff=3.0.2-SNAPSHOT
project.rel.org.jahia.modules\:addstuff=3.0.1
project.scm.org.jahia.modules\:addstuff.connection=scm\:git\:git@github.com\:jahia/addStuff.git
project.scm.org.jahia.modules\:addstuff.developerConnection=scm\:git\:git@github.com\:jahia/addStuff.git
project.scm.org.jahia.modules\:addstuff.tag=HEAD
projectVersionPolicyId=default
pushChanges=true
remoteTagging=true
scm.commentPrefix=[skip ci] [maven-release-plugin]
scm.tag=addstuff-3.0.1
scm.tagNameFormat=@{project.artifactId}-@{project.version}
scm.url=scm\:git\:git@github.com\:jahia/addStuff.git
