mutation applyAddStuff(
    $pathOrId: String!
    $headTop: String!
    $head: String!
    $bodyTop: String!
    $body: String!
) {
    jcr {
        mutateNode(pathOrId: $pathOrId) {
            addMixins(mixins: ["jmix:addStuff"])
            ht: mutateProperty(name: "addStuffHeadTop") { setValue(type: STRING, value: $headTop) }
            h:  mutateProperty(name: "addStuffHead")    { setValue(type: STRING, value: $head) }
            bt: mutateProperty(name: "addStuffBodyTop") { setValue(type: STRING, value: $bodyTop) }
            b:  mutateProperty(name: "addStuffBody")    { setValue(type: STRING, value: $body) }
        }
    }
}
